version: '3'

services:
  mqtt-broker:
    image: emqx/emqx
    environment:
      EMQX_MQTT__MAX_PACKET_SIZE: 10MB

  image-recognizer-aws:
    image: docker.pkg.github.com/parfy-io/image-recognizer/image-recognizer:latest
    environment:
      CFG_MQTT_BROKER: "mqtt-broker:1883"
      CFG_MQTT_CLIENT_ID: "aws"
      CFG_AWS_ACCESS_KEY: "<access_key>"
      CFG_AWS_SECRET_ACCESS_KEY: "<secret_access_key>"
      CFG_AWS_REGION: "eu-west-1"
      CFG_AWS_CONFIDENCE_MIN: 0
    depends_on:
      - mqtt-broker
    restart: always

  image-recognizer-azure:
    image: docker.pkg.github.com/parfy-io/image-recognizer/image-recognizer:latest
    environment:
      CFG_MQTT_BROKER: "mqtt-broker:1883"
      CFG_MQTT_CLIENT_ID: "azure"
      CFG_AZURE_REGION: "westeurope"
      CFG_AZURE_SUBSCRIPTION_KEY: "<subscription_key>"
    depends_on:
      - mqtt-broker
    restart: always

  text-mapper:
    image: docker.pkg.github.com/parfy-io/text-mapper/text-mapper:latest
    environment:
      CFG_MQTT_BROKER: "mqtt-broker:1883"
    depends_on:
      - mqtt-broker
    restart: always
    
  channel-manager:
    image: docker.pkg.github.com/parfy-io/channel-manager/channel-manager:latest
    environment:
      CFG_MQTT_BROKER: "mqtt-broker:1883"
    depends_on:
      - mqtt-broker
    restart: always

  mail-notifier:
    image: docker.pkg.github.com/parfy-io/mqtt-mail-notifier/mqtt-mail-notifier:latest
    environment:
      MMN_MAIL_SMTP_HOST: "smtp"
      MMN_MAIL_SMTP_PORT: 1025
      MMN_MAIL_SMTP_USERNAME: ""
      MMN_MAIL_SMTP_PASSWORD: ""
      MMN_MAIL_TLS_INSECURE_SKIP_VERIFY: "true"
      MMN_MAIL_TLS_SERVER_NAME: "smtp"
      MMN_MQTT_BROKER_ADDRESS: "mqtt-broker:1883"
      MMN_MQTT_CLIENT_ID: "mqtt-mail-notifier"
      MMN_USERS_SERVICE_BASE_URL: "http://user-service:8080"
    depends_on:
      - mqtt-broker
      - smtp
    restart: always

  smtp:
    image: mailhog/mailhog
    restart: always

